routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
})->name('index');
Route::get('/', 'Frontend\LandingPageController@index')->name('index');

Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('storage:link');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/areas', 'Backend\AreaController');
        Route::post('/areas/import/file', 'Backend\AreaController@importFile')->name('area.import.excel');
        Route::resource('/partners', 'Backend\UserController');
        Route::post('partners/excel', 'Backend\UserController@export')->name('partners.export');
        Route::resource('/customers', 'Backend\CustomerController');
        Route::post('customers/excel', 'Backend\CustomerController@export')->name('customers.export');
        Route::resource('/blogs', 'Backend\BlogController');
        Route::resource('/category-blogs', 'Backend\BlogCategoryController');
        Route::resource('/tag', 'Backend\TagController');
        Route::resource('/offers', 'Backend\OfferController');
        Route::resource('/orders', 'Backend\OrderController');
        Route::resource('/emailtemplates', 'Backend\EmailTemplatesController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });


});

//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('city_areas', 'Backend\AjaxController@cityArea')->name('cityAreas');
    Route::get('update/order/status', 'Backend\AjaxController@updateOrderStatus')->name('update.status');
});

Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);

Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Frontend Routes

//Partners Section
Route::get('/become-a-partner', 'Frontend\PartnerController@becomePartner')->name('become.partner');
Route::post('/save-partner', 'Frontend\PartnerController@savePartner')->name('save.partner');
Route::get('/partners', 'Frontend\PartnerController@existingPartner')->name('existing.partner');
Route::post('load/partners', 'Frontend\PartnerController@loadPartnerAjax')->name('partners.load.more');

//Blogs
Route::get('blogs', 'Frontend\BlogController@index')->name('blog');
Route::get('blog/{slug}', 'Frontend\BlogController@getBlog')->name('blog.show');
Route::post('load/blogs', 'Frontend\BlogController@loadBlogAjax')->name('blog.load.more');
Route::get('category/blog/{slug}', 'Frontend\BlogController@categoryBlog')->name('category.blogs');

//Reviews Section
Route::get('reviews/{id}', 'Frontend\RatingController@index')->name('partner.reviews');
Route::get('rating/{id}', 'Frontend\RatingController@rating')->name('partner.rating');
Route::post('store/rating', 'Frontend\RatingController@ratingStore')->name('partner.rating.store');
Route::post('load/reviews', 'Frontend\RatingController@loadReviewsAjax')->name('reviews.load.more');

//Solar Calculator
Route::get('solar/calculator', 'Frontend\GeneralController@solarCalculator')->name('solar.calculator');
Route::get('privacy-policy', 'Frontend\GeneralController@privacyPolicy')->name('privacy.policy');
Route::get('about-us', 'Frontend\GeneralController@aboutUs')->name('about-us');
Route::get('get-quote-now', 'Frontend\GeneralController@getQuoteNow')->name('get.quote.now');


//Offer Comparison
Route::get('offers', 'Frontend\OfferController@index')->name('offer.comparison.index');
Route::post('book/offer', 'Frontend\OrderController@store')->name('book.offer.store');
Route::get('update/order/status/{id}', 'Frontend\OrderController@updateOrderStatus')->name('update.offer.status');
Route::post('customer/order/confirmation', 'Frontend\OrderController@customerOrderConfirmation')->name('customer.order.confirmation');

//Thankyou

Route::get('thankyou', function () {
    return view('frontend.pages.thankyou');
})->name('thankyou');

Route::get('emails', function () {
    $user = \App\Models\User::first();
    $partner = \App\Models\User::first();
    $settings = \App\Models\Setting::first();
    $offer = \App\Models\Offer::first();
    $order = \App\Models\Order::first();

    return view('frontend.pages.comparison.email', compact('user', 'partner', 'settings', 'offer', 'order'));
});

app/Models/Aboutus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Aboutus extends Model
{
    protected $table = "aboutus";
    protected $guarded = [];
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::first();
        $description=$request->input('description');
        $dom = new \DomDocument();
        libxml_use_internal_errors(false);
        $dom->loadHtml($description, LIBXML_HTML_NOIMPLIED | # Make sure no extra BODY
            LIBXML_HTML_NODEFDTD |  # or DOCTYPE is created
            LIBXML_NOERROR |        # Suppress any errors
            LIBXML_NOWARNING        # or warnings about prefixes.
        );
        $images = $dom->getElementsByTagName('img');

        foreach($images as $k => $img){
            $data = $img->getAttribute('src');

            list($type, $data) = explode(';', $data);
            list(, $data)      = explode(',', $data);
            $data = base64_decode($data);

            $image_name= "/uploads/about_images" . time().$k.'.png';
            $path = public_path() . $image_name;

            file_put_contents($path, $data);

            $img->removeAttribute('src');
            $img->setAttribute('src', $image_name);
        }

        $description = $dom->saveHTML();


        if (!is_null($aboutus)) {
            $aboutus->update([
                'summary' => $request->summary,
                'description' => $request->description
            ]);
        } else {
            $aboutus = new Aboutus();
            $aboutus->summary = $request->summary;
            $aboutus->description = $request->description;
            $aboutus->save();
        }

        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Mail\RatingMail;
use App\Mail\VerifyMail;
use App\Models\Area;
use App\Models\EmailTemplates;
use App\Models\Order;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Session;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{
    public function cityArea(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'city_id' => 'required|exists:cities,id'
        ], [
            'city_id.required' => "City is Required.",
            'city_id.exists' => "Invalid City Selected."
        ]);

        if (!$validator->fails()) {
            $area = Area::where('city_id', $request->city_id)->get();

            $response['status'] = 'success';
            $response['data'] = [
                'area' => $area,
            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }

    public function updateOrderStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'order_id' => 'required|exists:orders,id'
        ], [
            'order_id.required' => "Order Id is Required.",
            'order_id.exists' => "Invalid Order Id Selected."
        ]);

        if (!$validator->fails()) {
            $order = Order::where('id', $request->get('order_id'))->update([
                'status' => $request->get('status'),
            ]);


            $order = Order::find($request->order_id);
            $user = User::where('id', $order->user_id)->first();
            $offer = User::where('id', $order->offer_id)->first();
            $partner = User::where('id', $order->partner_id)->first();


            $settings = Setting::first();
            $emailTemplate = EmailTemplates::where('type', 'feedback')->first();
            if ($request->get('status') == 'completed') {
                Mail::to($user->email)
                    ->bcc(['muhammad.atif@solarnest.pk', 'muhammad.mohsin@solarnest.pk', 'solarnestpk@gmail.com', 'info@solarnest.pk'])
//                    ->cc(['muhammad.atif@solarnest.pk', 'muhammad.mohsin@solarnest.pk', 'solarnestpk@gmail.com', 'info@solarnest.pk'])
                    ->send(new RatingMail($user, $order, $offer, $settings, $partner, $emailTemplate));

            }


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }


}

app/Http/Controllers/Backend/AreaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Area;
use App\Models\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\AreasImport;

class AreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $areas = Area::orderBy('id', 'DESC')->get();

        return view('backend.areas.index', compact('areas'));
    }

    public function create()
    {
        $cities = City::all();
        return view('backend.areas.create', compact('cities'));

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'price' => 'required',
            'city_id' => 'required'
        ], [
            'city_id.required' => 'City is required.'
        ]);
        Area::create($request->all());
        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area created successfully.'
            ]);

    }

    public function edit($id)
    {
        $area = Area::find($id);
        $cities = City::all();
        return view('backend.areas.edit', compact('area', 'cities'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'price' => 'required',
            'city_id' => 'required'
        ], [
            'city_id.required' => 'City is required.'
        ]);
        Area::find($id)->update($request->all());
        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $area = Area::findOrFail($id);
        $area->delete();

        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area has been deleted'
            ]);
    }

    public function importFile(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'file' => 'required|mimes:xls,xlsx'
        ]);
        if (!$validator->fails()) {

            Excel::import(new AreasImport(), $request->file('file'));

            $status = 'success';
            $message = 'Area File Imported Successfully.';
        } else {
            $status = 'error';
            $message = 'File Format is not correct or Incorrect Data.';
        }

        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => $status,
                'flash_message' => $message
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::where('user_type','partner')->get()->count();
        $customers_count = User::where('user_type','customer')->get()->count();
        $orders_count = Order::whereIn('status',['confirmed','completed'])->get()->count();
        return view('backend.dashboard.index', compact('users_count','customers_count','orders_count'));
    }
}

app/Http/Controllers/Frontend/AboutUsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('frontend.pages.aboutus-detail', compact('aboutus'));
    }
}

resources/views/backend/aboutus/create.blade.php
@extends('layouts.master')
@section('title','About US')

@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{ __('About Us') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.aboutus.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">
                                        <div class="col-md-12">


                                            <label for="summary"><strong>Summary</strong></label>

                                            <textarea name="summary" id="summary" rows="10" cols="144"
                                                      required>{{ ($aboutus) ? $aboutus->summary : '' }}</textarea>

                                            @error('summary')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-12">


                                            <label for="description"><strong>Description</strong></label>
                                            <div id="toolbar-container"></div>
                                            <textarea name="description" id="description" rows="10" cols="80"
                                                      required>{{ ($aboutus) ? $aboutus->description : '' }}</textarea>

                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                    </div>


                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#description').summernote({
                fontSizes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'],
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['fontsize', 'color']],
                    ['font', ['fontname']],
                    ['para', ['paragraph', 'ul', 'ol']],
                    ['insert', ['link', 'image', 'doc', 'video', 'picture', 'hr']], // image and doc are customized buttons
                    ['misc', ['codeview', 'fullscreen']],
                ],
                height: 400,
                dialogsInBody: true,
                callbacks: {
                    onInit: function () {
                        $('body > .note-popover').hide();
                    }
                },
            });
        });
    </script>
@endpush