routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
})->name('index');
Route::get('/', 'Frontend\LandingPageController@index')->name('index');

Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('storage:link');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/areas', 'Backend\AreaController');
        Route::post('/areas/import/file', 'Backend\AreaController@importFile')->name('area.import.excel');
        Route::resource('/partners', 'Backend\UserController');
        Route::post('partners/excel', 'Backend\UserController@export')->name('partners.export');
        Route::resource('/customers', 'Backend\CustomerController');
        Route::post('customers/excel', 'Backend\CustomerController@export')->name('customers.export');
        Route::resource('/blogs', 'Backend\BlogController');
        Route::resource('/category-blogs', 'Backend\BlogCategoryController');
        Route::resource('/tag', 'Backend\TagController');
        Route::resource('/offers', 'Backend\OfferController');
        Route::resource('/orders', 'Backend\OrderController');
        Route::resource('/emailtemplates', 'Backend\EmailTemplatesController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });


});

//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('city_areas', 'Backend\AjaxController@cityArea')->name('cityAreas');
    Route::get('update/order/status', 'Backend\AjaxController@updateOrderStatus')->name('update.status');
});

Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);

Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Frontend Routes

//Partners Section
Route::get('/become-a-partner', 'Frontend\PartnerController@becomePartner')->name('become.partner');
Route::post('/save-partner', 'Frontend\PartnerController@savePartner')->name('save.partner');
Route::get('/partners', 'Frontend\PartnerController@existingPartner')->name('existing.partner');
Route::post('load/partners', 'Frontend\PartnerController@loadPartnerAjax')->name('partners.load.more');

//Blogs
Route::get('blogs', 'Frontend\BlogController@index')->name('blog');
Route::get('blog/{slug}', 'Frontend\BlogController@getBlog')->name('blog.show');
Route::post('load/blogs', 'Frontend\BlogController@loadBlogAjax')->name('blog.load.more');
Route::get('category/blog/{slug}', 'Frontend\BlogController@categoryBlog')->name('category.blogs');

//Reviews Section
Route::get('reviews/{id}', 'Frontend\RatingController@index')->name('partner.reviews');
Route::get('rating/{id}', 'Frontend\RatingController@rating')->name('partner.rating');
Route::post('store/rating', 'Frontend\RatingController@ratingStore')->name('partner.rating.store');
Route::post('load/reviews', 'Frontend\RatingController@loadReviewsAjax')->name('reviews.load.more');

//Solar Calculator
Route::get('solar/calculator', 'Frontend\GeneralController@solarCalculator')->name('solar.calculator');
Route::get('privacy-policy', 'Frontend\GeneralController@privacyPolicy')->name('privacy.policy');
Route::get('about-us', 'Frontend\GeneralController@aboutUs')->name('about-us');
Route::get('get-quote-now', 'Frontend\GeneralController@getQuoteNow')->name('get.quote.now');


//Offer Comparison
Route::get('offers', 'Frontend\OfferController@index')->name('offer.comparison.index');
Route::post('book/offer', 'Frontend\OrderController@store')->name('book.offer.store');
Route::get('update/order/status/{id}', 'Frontend\OrderController@updateOrderStatus')->name('update.offer.status');
Route::post('customer/order/confirmation', 'Frontend\OrderController@customerOrderConfirmation')->name('customer.order.confirmation');

//Thankyou

Route::get('thankyou', function () {
    return view('frontend.pages.thankyou');
})->name('thankyou');

Route::get('emails', function () {
    $user = \App\Models\User::first();
    $partner = \App\Models\User::first();
    $settings = \App\Models\Setting::first();
    $offer = \App\Models\Offer::first();
    $order = \App\Models\Order::first();

    return view('frontend.pages.comparison.email', compact('user', 'partner', 'settings', 'offer', 'order'));
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = "orders";
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function partner()
    {
        return $this->belongsTo(User::class, 'partner_id', 'id');
    }

    public function offer()
    {
        return $this->belongsTo(Offer::class, 'offer_id', 'id');
    }
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::first();
        $description=$request->input('description');
        $dom = new \DomDocument();
        libxml_use_internal_errors(false);
        $dom->loadHtml($description, LIBXML_HTML_NOIMPLIED | # Make sure no extra BODY
            LIBXML_HTML_NODEFDTD |  # or DOCTYPE is created
            LIBXML_NOERROR |        # Suppress any errors
            LIBXML_NOWARNING        # or warnings about prefixes.
        );
        $images = $dom->getElementsByTagName('img');

        foreach($images as $k => $img){
            $data = $img->getAttribute('src');

            list($type, $data) = explode(';', $data);
            list(, $data)      = explode(',', $data);
            $data = base64_decode($data);

            $image_name= "/uploads/about_images" . time().$k.'.png';
            $path = public_path() . $image_name;

            file_put_contents($path, $data);

            $img->removeAttribute('src');
            $img->setAttribute('src', $image_name);
        }

        $description = $dom->saveHTML();


        if (!is_null($aboutus)) {
            $aboutus->update([
                'summary' => $request->summary,
                'description' => $request->description
            ]);
        } else {
            $aboutus = new Aboutus();
            $aboutus->summary = $request->summary;
            $aboutus->description = $request->description;
            $aboutus->save();
        }

        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Mail\RatingMail;
use App\Mail\VerifyMail;
use App\Models\Area;
use App\Models\EmailTemplates;
use App\Models\Order;
use App\Models\Setting;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Session;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{
    public function cityArea(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'city_id' => 'required|exists:cities,id'
        ], [
            'city_id.required' => "City is Required.",
            'city_id.exists' => "Invalid City Selected."
        ]);

        if (!$validator->fails()) {
            $area = Area::where('city_id', $request->city_id)->get();

            $response['status'] = 'success';
            $response['data'] = [
                'area' => $area,
            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }

    public function updateOrderStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'order_id' => 'required|exists:orders,id'
        ], [
            'order_id.required' => "Order Id is Required.",
            'order_id.exists' => "Invalid Order Id Selected."
        ]);

        if (!$validator->fails()) {
            $order = Order::where('id', $request->get('order_id'))->update([
                'status' => $request->get('status'),
            ]);


            $order = Order::find($request->order_id);
            $user = User::where('id', $order->user_id)->first();
            $offer = User::where('id', $order->offer_id)->first();
            $partner = User::where('id', $order->partner_id)->first();


            $settings = Setting::first();
            $emailTemplate = EmailTemplates::where('type', 'feedback')->first();
            if ($request->get('status') == 'completed') {
                Mail::to($user->email)
                    ->bcc(['muhammad.atif@solarnest.pk', 'muhammad.mohsin@solarnest.pk', 'solarnestpk@gmail.com', 'info@solarnest.pk'])
//                    ->cc(['muhammad.atif@solarnest.pk', 'muhammad.mohsin@solarnest.pk', 'solarnestpk@gmail.com', 'info@solarnest.pk'])
                    ->send(new RatingMail($user, $order, $offer, $settings, $partner, $emailTemplate));

            }


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }


}

app/Http/Controllers/Backend/AreaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Area;
use App\Models\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\AreasImport;

class AreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $areas = Area::orderBy('id', 'DESC')->get();

        return view('backend.areas.index', compact('areas'));
    }

    public function create()
    {
        $cities = City::all();
        return view('backend.areas.create', compact('cities'));

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'price' => 'required',
            'city_id' => 'required'
        ], [
            'city_id.required' => 'City is required.'
        ]);
        Area::create($request->all());
        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area created successfully.'
            ]);

    }

    public function edit($id)
    {
        $area = Area::find($id);
        $cities = City::all();
        return view('backend.areas.edit', compact('area', 'cities'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'price' => 'required',
            'city_id' => 'required'
        ], [
            'city_id.required' => 'City is required.'
        ]);
        Area::find($id)->update($request->all());
        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $area = Area::findOrFail($id);
        $area->delete();

        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Area has been deleted'
            ]);
    }

    public function importFile(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'file' => 'required|mimes:xls,xlsx'
        ]);
        if (!$validator->fails()) {

            Excel::import(new AreasImport(), $request->file('file'));

            $status = 'success';
            $message = 'Area File Imported Successfully.';
        } else {
            $status = 'error';
            $message = 'File Format is not correct or Incorrect Data.';
        }

        return redirect()->route('admin.areas.index')
            ->with([
                'flash_status' => $status,
                'flash_message' => $message
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::where('user_type','partner')->get()->count();
        $customers_count = User::where('user_type','customer')->get()->count();
        $orders_count = Order::whereIn('status',['confirmed','completed'])->get()->count();
        return view('backend.dashboard.index', compact('users_count','customers_count','orders_count'));
    }
}

resources/views/backend/orders/index.blade.php
@extends('layouts.master')
@section('title','Customer Orders')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Customer Offers
                        </h3>
                    </div>
                </div>

            </div>

            <div class="m-portlet__body">
                <div class="responsiveTable">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>

                            <th> Sr No</th>
                            <th> Partner Name</th>
                            <th> User Name</th>
                            <th> Proposal Number</th>
                            <th> Building</th>
                            <th> Size of Dwelling</th>
                            <th> System Wattage</th>
                            <th> Battery System</th>
                            <th> Proposal Document</th>
                            <th> Order Date</th>
                            <th> Status</th>
                            <th> Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($orders))
                            @foreach($orders as $order)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>
                                        <a href="{{route('admin.offers.edit',$order->offer_id)}}">{{$order->partner ? ucfirst($order->partner->company_name) : ''}}</a>
                                    </td>
                                    <td>{{$order->user ? ucfirst($order->user->fullname()) : ''}}</td>
                                    <td>{{$order->proposal_number }}</td>
                                    <td>{{$order->building_size ?? '--' }}</td>
                                    <td>{{$order->system_size_of_dwelling ?? '--' }}</td>
                                    <td>{{$order->offer ? $order->offer->system_wattage : '' }}</td>
                                    <td>{{$order->offer ? $order->offer->battery_system : '' }}</td>
                                    <td>
                                        <a href="{{ url('/storage/uploads/proposals/' . $order->id . '/solarnest.pdf' ) }}"
                                           target="_blank">Solarnest.pdf</a></td>
                                    <td>{{ date('d-m-Y',strtotime($order->created_at)) }}</td>
                                    <td style="width: 15%;">
                                        @if($order->status == 'completed')
                                            {{ucfirst($order->status)}}
                                        @else
                                            <select id="status"
                                                    class="form-control update-status @error('status') is-invalid @enderror"
                                                    name="status" autocomplete="status"
                                                    data-order-id="{{$order->id}}">
                                                <option
                                                    value="pending" {{ $order->status == 'pending' ? 'selected'  : '' }}>
                                                    Pending
                                                </option>
                                                <option
                                                    value="confirmed" {{ $order->status == 'confirmed' ? 'selected'  : '' }}>
                                                    Confirmed
                                                </option>
                                                <option
                                                    value="inprogress" {{ $order->status == 'inprogress' ? 'selected'  : '' }}>
                                                    In Progress
                                                </option>
                                                <option
                                                    value="completed" {{ $order->status == 'completed' ? 'selected'  : '' }}>
                                                    Completed
                                                </option>
                                            </select>
                                        @endif
                                    </td>
                                    <td class="d-flex">
                                        <form method="post"
                                              action="{{ route('admin.orders.destroy', $order->id) }}"
                                              id="delete_{{ $order->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <a class="btn btn-sm btn-danger m-left"
                                               href="javascript:void(0)"
                                               onclick="if(confirmDelete()){ document.getElementById('delete_<?=$order->id?>').submit(); }">
                                                Delete
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [7, 9]}
            ],
        });
        $(document).on('change', '.update-status', function () {

            form = $(this).closest('form');
            node = $(this);
            var status = $(this).val();
            var order_id = $(this).data('order-id');
            var request = {"status": status, "order_id": order_id};
            if (status !== '') {
                $.ajax({
                    type: "GET",
                    url: "{{ route('ajax.update.status') }}",
                    data: request,
                    dataType: "json",
                    cache: true,
                    success: function (response) {
                        if (response.status == "success") {
                            toastr['success']("Order Status Changed Successfully");
                        }
                    },
                    error: function () {
                        toastr['error']("Something Went Wrong.");
                    }
                });
            } else {
                toastr['error']("Please Select Status");
            }

        });


    </script>
@endpush